### ISSUE TITLE
分页pagging

### ISSUE THREAD

**Issue by weixiaopa** [alcedo-ui/alcedo-ui#1]
1、OFF状态下有10条数据，每页显示5条，会出现第三页为空。
![1](https://user-images.githubusercontent.com/17925783/28048070-145fa256-6621-11e7-915a-a25e588cc2f0.png)
2、在第一步的状态下，切换回ON状态，显示的位置仍是第三页，不是ON状态下（有4条数据）的第一页。
![2](https://user-images.githubusercontent.com/17925783/28048152-a6657e00-6621-11e7-8417-df9cd3a563d7.png)
![3](https://user-images.githubusercontent.com/17925783/28048171-c87533aa-6621-11e7-8276-35bfbdc0d631.png)
3、分页报错
![6](https://user-images.githubusercontent.com/17925783/28048589-87f98e9a-6624-11e7-8827-ec734884a10f.png)

**Comment by fatalxiao** [comment]
fixed in 1.0.55
