### ISSUE TITLE
[TreeSelect]当子节点全选后父节点也要被选中

### ISSUE THREAD

**Issue by weibo0909** [alcedo-ui/alcedo-ui#16]
![image](https://user-images.githubusercontent.com/15992076/40757675-45187036-64bc-11e8-9aaf-d52df81bc113.png)

**Comment by weibo0909** [comment]
还有就是displayField设置无效

**Comment by weibo0909** [comment]
当外部传入triggerValue的值时，应该优先显示外部传入的triggerValue

**Comment by fatalxiao** [comment]
fixed in 2.25.3
