### ISSUE TITLE
自动补全输入框 autoComplete

### ISSUE THREAD

**Issue by weixiaopa** [alcedo-ui/alcedo-ui#2]
1、输入时报错
![4](https://user-images.githubusercontent.com/17925783/28048521-1cef31b8-6624-11e7-822d-4d7b08c410fa.png)
![5](https://user-images.githubusercontent.com/17925783/28048522-1f2cbfe0-6624-11e7-91a5-0679544c2dcf.png)

**Comment by fatalxiao** [comment]
It has fixed in 1.0.53. Please update a new version.
