### ISSUE TITLE
table

### ISSUE THREAD

**Issue by weixiaopa** [alcedo-ui/alcedo-ui#3]
1、表头排序图标当没有点击时，图标显示错误。
![table1](https://user-images.githubusercontent.com/17925783/28297575-4e9240b6-6ba1-11e7-9954-eb07dc23209e.png)

2、table全选没作用。
![table2](https://user-images.githubusercontent.com/17925783/28297593-6e869872-6ba1-11e7-88e7-a812941bd561.png)

3、th部分全选按钮与下面列表的选择按钮没有对齐。
![table](https://user-images.githubusercontent.com/17925783/28297350-ff148c16-6b9f-11e7-991b-18df5d16b92f.png)

**Comment by fatalxiao** [comment]
fixed in 1.0.79
