### ISSUE TITLE
[DraggableGrid] 是否点击右侧图标时才可拖动；当一行不足5个时是否默认撑开；

### ISSUE THREAD

**Issue by weixiaopa** [alcedo-ui/alcedo-ui#8]
1、请添加点击右侧图标时才可拖动的配置项。
![222](https://user-images.githubusercontent.com/17925783/29157183-4e9e1622-7dd8-11e7-9228-52278f487e30.png)

2、请添加设置一行5个，但不够5个时是否还默认撑开的配置项。（当前设置为5个，实际有4个，未撑开）
![222](https://user-images.githubusercontent.com/17925783/29157151-1ff65ce4-7dd8-11e7-83f0-eb80959a97b6.png)

**Comment by fatalxiao** [comment]
Done in 1.0.92
